routes/admin.php
<?php
Route::group(['prefix' => 'admin'], function () {

    Route::group(['middleware' => 'admin'], function (){

        Route::get('/', function () {
            return view('admin.main');
        })->name('admin.home');

        Route::resource('categories','Admin\CategoryController');
        Route::patch("categorises/quick/{category}", "Admin\CategoryController@quickButtons")->name("quick.buttons");

        Route::resource('subcategories','Admin\SubCategoryController');

        Route::get("parent/add", "Admin\SubCategoryController@parent")->name("add.parent");
        Route::post("parent/create", "Admin\SubCategoryController@createParent")->name("create.parent");
        Route::patch("parent/update/{subcategory}", "Admin\SubCategoryController@updateParent")->name("update.parent");

        Route::get("child/add", "Admin\SubCategoryController@child")->name("add.child");
        Route::post("child/create", "Admin\SubCategoryController@createChild")->name("create.child");

        Route::patch("subcategories/quick/{subcategory}", "Admin\SubCategoryController@quickButtons")->name("sub.quick.buttons");

        Route::resource('products','Admin\AdminProductController');
        Route::patch("products/quick/{product}", "Admin\AdminProductController@quickButtons")->name("products.quick.buttons");
        Route::patch("products/rejected/{product}", "Admin\AdminProductController@rejected")->name("products.rejected.button");
        Route::get("filter/products", "Admin\AdminProductController@filter")->name("products.filter");

        Route::resource('settings','Admin\GpuShopSettingController');
        Route::resource('slider','Admin\AdminSliderController');


    });


    Route::get("login", "Auth\Admin\LoginController@showLoginForm")->name("admin.loginForm");
    Route::post("login", "Auth\Admin\LoginController@login")->name('admin.login');
    Route::post("logout", "Auth\Admin\LoginController@logout")->name("admin.logout");

    Route::get('/test2', function () {
        $output = "
            //remove comment
            this1 //remove comment
            this2 /* remove comment */
            this3 /* remove
            comment */
            this4 /* * * remove
            * * * *
            comment * * */
            this5 http://removecomment.com
            id = id.replace(/\//g,''); //do not remove the regex //
            HTTP+'//www.googleadservices.com/pagead/conversion'
            ";

        $pattern = '/(?:(?:\/\*(?:[^*]|(?:\*+[^*\/]))*\*+\/)|(?:(?<!\:|\\\|\')\/\/.*))/';
        $output = preg_replace($pattern, '', $output);

        echo nl2br($output);
    });

    Route::get("test", "Test@test");


});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get("/", 'Client\ClientsHomePageController@homepage')->name('homepage');

Route::group(['middleware' => 'client'], function () {

    Route::prefix('profile')->group(function () {
        Route::get('/', 'Client\ProfileClientController@show')->name('client.profile');
        Route::put('/', 'Client\ProfileClientController@update')->name('update.client.profile');

        Route::get('phone/verify', 'Client\PhoneVerifyClientController@index')->name('verify.phone.client');
        Route::post('phone/verify', 'Client\PhoneVerifyClientController@create')->name('code.phone.client');
        Route::get('verify/code', 'Client\PhoneVerifyClientController@show')->name('verify.page.client');
        Route::post('verify/code', 'Client\PhoneVerifyClientController@update')->name('verify.code.client');
    });

    Route::get('wishlist', 'Client\ClientWishlistController@index')->name('show.wishlist.client');
    // axios wishlist
    Route::post('wishlist/{id}', 'Client\ClientWishlistController@storeWishlist');
    Route::put('vcisibility/{wishlist}', 'Client\ClientWishlistController@visibilityWishlist');
    Route::put('wishlist/move/{id}/{anotherId}/{up}', 'Client\ClientWishlistController@moveWishlist');
    Route::put('wishlist/move/{id}/{up}', 'Client\ClientWishlistController@topOrBottomWishlist');
    Route::delete('wishlist/{id}', 'Client\ClientWishlistController@destroyWishlistInProducts');
    Route::delete('wishlist/page/{wishlist}', 'Client\ClientWishlistController@destroyWishlist');

    Route::get('cart', 'Client\ClientCartController@index')->name('cart.client');
    Route::post('cart/add/{product}', 'Client\ClientCartController@addCart');
    Route::put('cart/page/{product}', 'Client\ClientCartController@addProductCart');
    Route::put('cart/qty/{index}/{qty}', 'Client\ClientCartController@qtyCart');
    Route::patch('cart/coupon/{coupon}', 'Client\ClientCartController@coupon')
        ->middleware('throttle:5,1');
    Route::delete('cart/remove/coupon', 'Client\ClientCartController@removeCoupon');
    Route::delete('cart/remove/{index}', 'Client\ClientCartController@removeProductCart');

    Route::get('orders', 'Client\OrderController@index')->name('orders.client');
    Route::get('orders/{order}', 'Client\OrderController@show')->name('order.client');
    Route::post('orders', 'Client\OrderController@delivered')->name('delivered.client');
    Route::get('checkout', 'Client\OrderController@create')->name('checkout.client');
    Route::post('checkout', 'Client\OrderController@store')->name('create.checkout.client');
    Route::get('confirm', 'Client\OrderController@confirm')->name('confirm.checkout.client');
    Route::get('paypal/checkout', 'Client\OrderController@paypalCheckout')->name('checkout.paypal.client');
    Route::get('paypal/cancel', 'Client\OrderController@paypalCancel')->name('cancel.paypal.client');

    Route::post('rating', 'Client\ClientProductController@rating')
        ->name('create.rating.client')
        ->middleware('throttle:5,1');

    Route::post('comment/store/{product}', 'CommentController@store');
    Route::patch('comment/update', 'CommentController@update');
    Route::delete('comment/delete/{id}', 'CommentController@delete');

    Route::get('notification', 'Client\ProfileClientController@notification')->name('notification.client');
    Route::put('notification/read', 'Client\ProfileClientController@readNotification')->name('read.notification.client');
    Route::patch('notification/read/{id}', 'Client\ProfileClientController@aReadNotification')->name('read.notification.client');
});

// Authentication Routes
Route::get("login", "Auth\Client\LoginController@showLoginForm")->name("client.loginForm")->middleware('guest:client');
Route::post("login", "Auth\Client\LoginController@phoneOrEmail")->name('client.login');
Route::post("logout", "Auth\Client\LoginController@logout")->name("client.logout");
// Registration Routes
Route::get('register', 'Auth\Client\RegisterController@showRegistrationForm')->name('client.registerForm');
Route::post('register', 'Auth\Client\RegisterController@register')->name('client.register');
Route::get('register/verify', 'Auth\Client\VerificationController@verify')->name('client.email.verifyForm');
Route::get('register/verify/resend', 'Auth\Client\VerificationController@resend')->name('client.email.verifyResend');
// Facebook Login
Route::get('login/facebook', 'Auth\Client\LoginController@redirectToProvider')->name('login.facebook');
Route::get('login/facebook/callback', 'Auth\Client\LoginController@handleProviderCallback')->name('callback.facebook');

// Password Reset Routes
Route::get('password/reset', 'Auth\Client\ForgotPasswordController@showLinkRequestForm')
    ->name('client.password.request');
Route::post('password/email', 'Auth\Client\ForgotPasswordController@sendResetLinkEmail')
    ->name('client.password.email');
Route::get('password/reset/{token}', 'Auth\Client\ResetPasswordController@showResetForm')
    ->name('client.password.reset');
Route::post('password/reset', 'Auth\Client\ResetPasswordController@reset')
    ->name('client.password.update');
// Password Reset Routes Via Phone
Route::get('password/phone/{phone}', 'Client\PhoneVerifyClientController@showFormMessage')
    ->name('client.password.reset.phone');
Route::post('password/phone', 'Client\PhoneVerifyClientController@sendResetCode')
    ->name('client.send.reset.password');
Route::get('password/phone/code/{phone}', 'Client\PhoneVerifyClientController@checkCodeForm')
    ->name('client.check.code.password');
Route::post('password/phone/code', 'Client\PhoneVerifyClientController@checkCode')
    ->name('client.code.password');
Route::get('password/change/phone/{phone}/{code}', 'Client\PhoneVerifyClientController@changePasswordForm')
    ->name('client.change.password.form');
Route::post('password/change/phone', 'Client\PhoneVerifyClientController@changePassword')
    ->name('client.change.password.phone');


Route::get("search", "Client\ClientProductController@search")->name('search.product');
Route::get("s/{subcategory}", "SubcatProductController@show")->name('show.products');
Route::get('p/{product}', 'Client\ClientProductController@show')->name('show.product.client');
Route::get('hot-sale', 'Client\ClientProductController@hotSale')->name('hotSale.client');
Route::get('f/{subcategory}/', 'SubcatProductController@filter')->name('filter.product.client');
Route::get('offer/{subcategory}/', 'SubcatProductController@showOffers')->name('offers.product.client');
Route::get('change/currency', 'Client\ClientController@currency')->name('currency.product.client');

Route::get('wishlists/{client}', 'Client\ClientWishlistController@show')->name('show.wishlist.guest');
Route::get('profile/{username}', 'Client\ProfileClientController@index')->name('view.profile');


Route::get('/test', function () {
    return sliderImages();
});

resources/views/admin/product/index.blade.php
@extends('admin.app')
@push('styles')
    <style>
    body {
    color: #6b7381;
    background: #f2f2f2;
    }
    .example .btn-toggle {
    top: 50%;
    transform: translateY(-50%);
    }
    .btn-toggle {
    margin: 0 4rem;
    padding: 0;
    position: relative;
    border: none;
    height: 1.5rem;
    width: 3rem;
    border-radius: 1.5rem;
    color: #6b7381;
    background: #bdc1c8;
    }
    .btn-toggle:focus,
    .btn-toggle.focus,
    .btn-toggle:focus.active,
    .btn-toggle.focus.active {
    outline: none;
    }
    .btn-toggle:before,
    .btn-toggle:after {
    line-height: 1.5rem;
    width: 4rem;
    text-align: center;
    font-weight: 600;
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 2px;
    position: absolute;
    bottom: 0;
    transition: opacity .25s;
    }
    .btn-toggle:before {
    content: 'D';
    left: -4rem;
    }
    .btn-toggle:after {
    content: 'E';
    right: -4rem;
    opacity: .5;
    }
    .btn-toggle > .handle {
    position: absolute;
    top: 0.1875rem;
    left: 0.1875rem;
    width: 1.125rem;
    height: 1.125rem;
    border-radius: 1.125rem;
    background: #fff;
    transition: left .25s;
    }
    .btn-toggle.active {
    transition: background-color 0.25s;
    }
    .btn-toggle.active > .handle {
    left: 1.6875rem;
    transition: left .25s;
    }
    .btn-toggle.active:before {
    opacity: .5;
    }
    .btn-toggle.active:after {
    opacity: 1;
    }
    .btn-toggle.btn-sm:before,
    .btn-toggle.btn-sm:after {
    line-height: -0.5rem;
    color: #fff;
    letter-spacing: .75px;
    left: 0.41250000000000003rem;
    width: 2.325rem;
    }
    .btn-toggle.btn-sm:before {
    text-align: right;
    }
    .btn-toggle.btn-sm:after {
    text-align: left;
    opacity: 0;
    }
    .btn-toggle.btn-sm.active:before {
    opacity: 0;
    }
    .btn-toggle.btn-sm.active:after {
    opacity: 1;
    }

    .btn-toggle:before,
    .btn-toggle:after {
    color: #6b7381;
    }
    .btn-toggle.active {
    background-color: #29b5a8;
    }

    .btn-toggle.btn-sm {
    margin: 0 0.5rem;
    padding: 0;
    position: relative;
    border: none;
    height: 1.5rem;
    width: 3rem;
    border-radius: 1.5rem;
    }
    .btn-toggle.btn-sm:focus,
    .btn-toggle.btn-sm.focus,
    .btn-toggle.btn-sm:focus.active,
    .btn-toggle.btn-sm.focus.active {
    outline: none;
    }
    .btn-toggle.btn-sm:before,
    .btn-toggle.btn-sm:after {
    line-height: 1.5rem;
    width: 0.5rem;
    text-align: center;
    font-weight: 600;
    font-size: 0.55rem;
    text-transform: uppercase;
    letter-spacing: 2px;
    position: absolute;
    bottom: 0;
    transition: opacity .25s;
    }
    .btn-toggle.btn-sm:before {
    content: 'Not';
    left: -0.5rem;
    }
    .btn-toggle.btn-sm:after {
    content: 'App';
    right: -0.5rem;
    opacity: .5;
    }
    .btn-toggle.btn-sm > .handle {
    position: absolute;
    top: 0.1875rem;
    left: 0.1875rem;
    width: 1.125rem;
    height: 1.125rem;
    border-radius: 1.125rem;
    background: #fff;
    transition: left .25s;
    }
    .btn-toggle.btn-sm.active {
    transition: background-color 0.25s;
    }
    .btn-toggle.btn-sm.active > .handle {
    left: 1.6875rem;
    transition: left .25s;
    }
    .btn-toggle.btn-sm.active:before {
    opacity: .5;
    }
    .btn-toggle.btn-sm.active:after {
    opacity: 1;
    }
    .btn-toggle.btn-sm.btn-sm:before,
    .btn-toggle.btn-sm.btn-sm:after {
    line-height: -0.5rem;
    color: #fff;
    letter-spacing: .75px;
    left: 0.41250000000000003rem;
    width: 2.325rem;
    }
    .btn-toggle.btn-sm.btn-sm:before {
    text-align: right;
    }
    .btn-toggle.btn-sm.btn-sm:after {
    text-align: left;
    opacity: 0;
    }
    .btn-toggle.btn-sm.btn-sm.active:before {
    opacity: 0;
    }
    .btn-toggle.btn-sm.btn-sm.active:after {
    opacity: 1;
    }

    .btn-toggle.btn-xs.active > .handle {
    left: 1.125rem;
    transition: left .25s;
    }

    button.btn:hover,
    a.btn:hover {
        -webkit-transform: scale(1);
        -moz-transform: scale(1);
        -o-transform: scale(1);
    }
    button.btn,
    a.btn {
        -webkit-transform: scale(0.8);
        -moz-transform: scale(0.8);
        -o-transform: scale(0.8);
        -webkit-transition-duration: 0.5s;
        -moz-transition-duration: 0.5s;
        -o-transition-duration: 0.5s;
    }
    td p span{
        color: dodgerblue;
    }

</style>
@endpush
@section('content')
    <div class="container-fluid">
        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Products</h1>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary d-inline" >All Products</h6>

            <a href="{{route('products.create')}}" class="btn btn-primary a-btn-slide-text float-right">
                <span class="fa fa-plus" aria-hidden="true"></span>
                <span><strong>{{__('Add')}}</strong></span>
            </a>
            @php $filter = !empty($request) ? $request : null @endphp
            <form method="GET" action="{{ route('products.filter') }}">
                <div class="form-row">
                    <div class="form-group col-md-5">
                        <label for="inputName">Name of Product</label>
                        <input type="text" class="form-control" value="{{ $filter ? $filter->name : ''}}" id="inputName" name="name" placeholder="Name">
                    </div>
                    <div class="form-group col-md-5">
                        <label for="Username">Seller Username</label>
                        <input type="text" class="form-control" id="Username"  value="{{$filter ? $filter->username : ''}}" name="username" placeholder="Username">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-5">
                        <label for="Price">Price</label>
                        <input type="number" class="form-control" id="Price" value="{{$filter ? $filter->price : ''}}" name="price" placeholder="Price">
                    </div>
                    <div class="form-group col-md-1.5">
                        @php $select = !empty($request) ? $request->currency : null @endphp
                        <label for="currency">Currency</label>
                        <select id="currency" name="currency" class="form-control">
                            <option value="egp" selected>EGP</option>
                            <option value="usd" {{$select == 'usd' ? 'selected' : '' }}>USD</option>
                        </select>
                    </div>
                    @php $select = !empty($request) ? $request->status : null @endphp
                    <div class="form-group col-md-4">
                        <label for="inputState">Status</label>
                        <select id="inputState" name="status" class="form-control">
                            <option  selected></option>
                            <option value="1" {{$select == 1 ? 'selected' : '' }}>Approved</option>
                            <option value="0" {{$select == 0 ? 'selected' : '' }}>Not Approved</option>
                            <option value="2" {{$select == 2 ? 'selected' : '' }}>Rejected</option>
                        </select>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
            </form>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Approved</th>
                        <th>Price</th>
                        <th>Seller Username</th>
                        <th>Quick Buttons</th>
                        <th>Edit</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($products as $product)
                        @php
                            $approved = $product->approved ;
                        @endphp
                    <tr>
                        <td>{{$product->name}}</td>
                        <td>@if($approved == 1) Approved @elseif($approved == 2) Rejected @else Not approved @endif</td>
                        <td >
                            <p>{{$product->price_egp}} <span>EGP</span></p>
                            <p>{{$product->price_usd}} <span>USD</span></p>
                        </td>
                        <td>{{$product->seller->username }}</td>
                        <td width="25%">
                            {!! Form::model(['method'=>'PATCH' ],['route' => ['products.quick.buttons',$product] ,'class'=>'d-inline'] ) !!}
                            @method('PATCH')
                            <button type="button"  onclick="myFunction({{$product->id}})" class="btn btn-sm btn-toggle {{$approved == 1 ? 'active' : ''}}" data-toggle="button" aria-pressed="true" autocomplete="off">
                                <div class="handle"></div>
                            </button>
                            {!! Form::submit ("",['hidden','id'=>$product->id]) !!}
                            {!! Form::close() !!}

                            <form class="d-inline" method="post" action="{{route('products.rejected.button',$product)}}">
                                @method('PATCH')
                                @csrf
                                <button type="submit" class="btn btn-danger btn-circle">
                                    <i class="fas fa-exclamation-triangle"></i>
                                </button>
                            </form>

                            <form class="d-inline" method="post" action="{{route('products.destroy',$product)}}">
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="btn btn-danger btn-circle">
                                <i class="fas fa-trash"></i>
                                </button>
                            </form>
                            <a href="{{route('show.product.client',[$product])}}" class="btn btn-info btn-circle">
                                <i class="fa fa-eye"></i>
                            </a>
                        </td>
                        <td width="15%">
                            <div class=" text-center">
                            <a href="{{route('products.edit',[$product])}}" class="btn btn-primary a-btn-slide-text">
                                <span class="fa fa-wrench" aria-hidden="true"></span>
                                <span><strong>Edit</strong></span>
                            </a>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    </div>
    <!-- /.container-fluid -->
    @include('admin.layout.alert')
@endsection
@push('scripts')
<script>
    function myFunction(id) {
        document.getElementById(id).click();
    }
</script>
@endpush